input NewEntryInput {
  title: String!
  body: String!
}

input UpdateEntryInput {
  id: ID!
  title: String
  body: String
  mode: String!
}

type ERROR {
  field: String!
  message: String!
}
type Entry {
  id: ID!
  title: String!
  body: String!
  updatedAt: String!
  createdAt: String!
}
type EntryData {
  entry: Entry!
  errors: [ERROR!]
}

extend type Mutation {
  createEntry(input: NewEntryInput!): EntryData
  updateEntry(input: UpdateEntryInput!): EntryData
}

extend type Query {
  listAllEntries: [Entry!]
}
