input NewEntryInput {
  title: String!
  body: String!
}

type ERROR {
  field: String!
  message: String!
}
type Entry {
  id: ID
  title: String
  body: String
}
type EntryData {
  entry: Entry
  errors: [ERROR!]
}

extend type Mutation {
  createEntry(input: NewEntryInput!): EntryData
}

extend type Query {
  listAllEntry: [Entry!]
}
