version: "3.9"


services: 
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes: 
      - "./:/usr/app"
      - "/usr/app/node_modules"
    ports:
      - 4000:4000
    env_file:
      - .env
    depends_on: 
      - db
  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    volumes: 
      - journal_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=journal
      - POSTGRES_USER=gozman
      - POSTGRES_PASSWORD=password

  
volumes:
  journal_data: